name: Build Programs

on:
  workflow_call:
    inputs:
      rust:
        type: string
      miraland:
        type: string
  workflow_dispatch:
    inputs:
      rust:
        description: Rust version
        default: 1.65.0
        required: true
        type: string
      miraland:
        description: Miraland version
        default: 1.14.17
        required: true
        type: string

env:
  CACHE: true

jobs:
  build_programs:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Git checkout
        uses: actions/checkout@v3

      - name: Load environment variables
        run: cat .github/.env >> $GITHUB_ENV

      - name: Install Rust
        uses: metaplex-foundation/actions/install-rust@v1
        with:
          toolchain: ${{ inputs.rust || env.RUST_VERSION }}

      - name: Install Miraland
        uses: metaplex-foundation/actions/install-miraland@v1
        with:
          version: ${{ inputs.miraland || env.MIRALAND_VERSION }}
          cache: ${{ env.CACHE }}

      - name: Cache program dependencies
        if: env.CACHE == 'true'
        uses: metaplex-foundation/actions/cache-programs@v1

      - name: Build programs
        env:
          PROGRAMS: ${{ env.PROGRAMS }}
        run: |
          for program in $(echo $PROGRAMS | jq -c '.[]' | sed 's/"//g'); do
            (cd ./programs/$program; cargo build-bpf)
          done

      - name: Upload program builds
        uses: actions/upload-artifact@v3
        with:
          name: program-builds
          # First wildcard ensures exported paths are consistently under the programs folder.
          path: ./program*/**/target/deploy/*.so
          if-no-files-found: error
